
[package]
name = "sema"
version = "0.1.0"
edition = "2024"

[lib]
name = "sema"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.103"

ra_ap_ide_db = "=0.0.339"
ra_ap_vfs = "=0.0.339"
ra_ap_syntax = "=0.0.339"
ra_ap_paths = "=0.0.339"
ra_ap_load-cargo    = "=0.0.339"
ra_ap_project_model = "=0.0.339"
ra_ap_base_db       = "=0.0.339"
ra_ap_hir           = "=0.0.339"
camino              = "1"

syn = { version = "2.0", features = ["full", "derive"] }
fnv = "1.0.7"

